# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\autorization\autorization_tg\autoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization_tg(object):
    def setupUi(self, authorization_tg):
        authorization_tg.setObjectName("authorization_tg")
        authorization_tg.resize(360, 186)
        self.line_number_phone = QtWidgets.QLineEdit(authorization_tg)
        self.line_number_phone.setGeometry(QtCore.QRect(20, 30, 161, 31))
        self.line_number_phone.setObjectName("line_number_phone")
        self.line_code = QtWidgets.QLineEdit(authorization_tg)
        self.line_code.setEnabled(False)
        self.line_code.setGeometry(QtCore.QRect(20, 80, 161, 31))
        self.line_code.setObjectName("line_code")
        self.line_password = QtWidgets.QLineEdit(authorization_tg)
        self.line_password.setEnabled(False)
        self.line_password.setGeometry(QtCore.QRect(20, 130, 161, 31))
        self.line_password.setObjectName("line_password")
        self.btn_autorization = QtWidgets.QPushButton(authorization_tg)
        self.btn_autorization.setEnabled(False)
        self.btn_autorization.setGeometry(QtCore.QRect(210, 132, 131, 31))
        self.btn_autorization.setObjectName("btn_autorization")
        self.btn_give_code = QtWidgets.QPushButton(authorization_tg)
        self.btn_give_code.setGeometry(QtCore.QRect(210, 30, 131, 31))
        self.btn_give_code.setObjectName("btn_give_code")

        self.retranslateUi(authorization_tg)
        QtCore.QMetaObject.connectSlotsByName(authorization_tg)

    def retranslateUi(self, authorization_tg):
        _translate = QtCore.QCoreApplication.translate
        authorization_tg.setWindowTitle(_translate("authorization_tg", "Авторизация в телеграмме"))
        self.line_number_phone.setPlaceholderText(_translate("authorization_tg", "Номер телефона (89**)"))
        self.line_code.setPlaceholderText(_translate("authorization_tg", "Код из телеграмма"))
        self.line_password.setPlaceholderText(_translate("authorization_tg", "Пароль (если есть)"))
        self.btn_autorization.setText(_translate("authorization_tg", "Войти"))
        self.btn_give_code.setText(_translate("authorization_tg", "Получить код"))
