# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AutorizationUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 203)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setGeometry(QtCore.QRect(20, 100, 211, 31))
        self.line_login.setObjectName("line_login")
        self.line_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass.setGeometry(QtCore.QRect(240, 100, 211, 31))
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.btn_autorizade = QtWidgets.QPushButton(self.centralwidget)
        self.btn_autorizade.setGeometry(QtCore.QRect(180, 150, 111, 31))
        self.btn_autorizade.setObjectName("btn_autorizade")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("auto.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line_login.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.line_pass.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.btn_autorizade.setText(_translate("MainWindow", "Войти"))
