# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\autorization_application\autoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization_app(object):
    def setupUi(self, authorization_app):
        authorization_app.setObjectName("authorization_app")
        authorization_app.resize(468, 214)
        self.label = QtWidgets.QLabel(authorization_app)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\autorization_application\\../auto.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line_login = QtWidgets.QLineEdit(authorization_app)
        self.line_login.setGeometry(QtCore.QRect(20, 120, 211, 31))
        self.line_login.setObjectName("line_login")
        self.line_pass = QtWidgets.QLineEdit(authorization_app)
        self.line_pass.setGeometry(QtCore.QRect(240, 120, 211, 31))
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.btn_autorizade = QtWidgets.QPushButton(authorization_app)
        self.btn_autorizade.setGeometry(QtCore.QRect(310, 160, 141, 31))
        self.btn_autorizade.setObjectName("btn_autorizade")

        self.retranslateUi(authorization_app)
        QtCore.QMetaObject.connectSlotsByName(authorization_app)

    def retranslateUi(self, authorization_app):
        _translate = QtCore.QCoreApplication.translate
        authorization_app.setWindowTitle(_translate("authorization_app", "Авторизация в приложении"))
        self.line_login.setPlaceholderText(_translate("authorization_app", "Логин"))
        self.line_pass.setPlaceholderText(_translate("authorization_app", "Пароль"))
        self.btn_autorizade.setText(_translate("authorization_app", "Войти"))


