# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Python\Uploader\autorization\autorization_sites\UI_saites.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(329, 222)
        Form.setMinimumSize(QtCore.QSize(329, 222))
        Form.setMaximumSize(QtCore.QSize(329, 222))
        Form.setStyleSheet("QWidget{\n"
"    background-color:rgb(49, 54, 65) ;\n"
"}\n"
"QToolTip {\n"
"        color: black; /* Цвет текста */\n"
"        background-color: white; /* Цвет фона */\n"
"        border: 1px solid black; /* Граница */\n"
"        font: 12px; /* Шрифт */\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(49, 54, 65);\n"
"    border:none;\n"
"    border-radius:0px;\n"
"}\n"
"/* Стиль кнопок */\n"
"QPushButton {\n"
"    background-color: rgb(38, 42, 51);\n"
"    color: rgb(52, 181, 249); /* текст в кнопках светлее голубой */\n"
"    border: none;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 50, 60);\n"
"    color: rgb(52, 181, 249); /* текст в кнопках светлее голубой */\n"
"    border: 1px solid rgb(0, 72, 127);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgba(52, 181, 249,50%);\n"
"    background-color: rgba(38, 42, 51,50%);\n"
"}\n"
"\n"
"/* Стиль прогрессбара */\n"
"QProgressBar {\n"
"    background-color: rgb(38, 42, 51);\n"
"    color: rgb(49, 54, 65);\n"
"    border-radius: 10px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(52, 181, 249, 255), stop:1 rgba(0, 116, 211, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"/* Стиль чекбоксов */\n"
"QCheckBox {\n"
"    color: rgb(140, 151, 170); /* светлосерый текст */\n"
"    border: none;\n"
"    spacing:10px;\n"
"    font-size:15px;\n"
"}\n"
"QCheckBox::indicator{\n"
"    width:15px;\n"
"    height:15px;\n"
"}\n"
"QCheckBox::indicator:unchecked{\n"
"    image: url(:/ckeckbox/icon/checkbox_unchecked.ico);\n"
"}\n"
"QCheckBox::indicator:unchecked:hover, QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(:/ckeckbox/icon/checkbox_unchecked_hover_pressed.ico);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    image: url(:/ckeckbox/icon/checkbox_checked.ico);\n"
"}\n"
"QCheckBox::indicator:checked:hover, QCheckBox::indicator:checked:pressed {\n"
"image: url(:/ckeckbox/icon/checkbox_checked_hover_pressed.ico);\n"
"}\n"
"QCheckBox:hover {\n"
"    color:rgb(52, 181, 249);\n"
"}\n"
"QCheckBox::disabled{\n"
"    color: rgba(140, 151, 170,30%);\n"
"}\n"
"\n"
"/* Стиль текстового поля */\n"
"QTextEdit, QLineEdit {\n"
"    background-color: rgb(38, 42, 51);\n"
"    color: rgb(140, 151, 170); /* светлосерый текст */\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"/* Стиль стакедвиджета */\n"
"QStackedWidget {\n"
"    background-color: rgb(38, 42, 51);\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(140, 151, 170);\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"        background: rgb(38, 42, 51);\n"
"        width: 12px;\n"
"        margin: 0px 0px 0px 0px;\n"
"    }\n"
"QScrollBar::handle:vertical {\n"
"        background: rgb(49, 54, 65);\n"
"        min-height: 20px;\n"
"    }\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: rgb(52, 181, 249);\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"        background: rgb(38, 42, 51);\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"        background: rgb(38, 42, 51);\n"
"        height: 0px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }\n"
"\n"
"rgb(38, 42, 51) темно серый\n"
"rgb(49, 54, 65) тоже темно серый, чутка светлее\n"
"rgb(140, 151, 170) светлосерый текст\n"
"\n"
"rgb(0, 116, 211) голубой\n"
"rgb(42, 150, 255) светлоголубой\n"
"rgb(52, 181, 249) еще  светлее голубой")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 10, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-10, 110, 251, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(999999, 999999))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 180, 191, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 140, 191, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.btn_auto_animaunt = QtWidgets.QPushButton(Form)
        self.btn_auto_animaunt.setGeometry(QtCore.QRect(230, 52, 91, 31))
        self.btn_auto_animaunt.setObjectName("btn_auto_animaunt")
        self.btn_auto_malf = QtWidgets.QPushButton(Form)
        self.btn_auto_malf.setGeometry(QtCore.QRect(230, 160, 91, 31))
        self.btn_auto_malf.setObjectName("btn_auto_malf")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">AniMaunt</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Malfurik</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Пароль"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Пароль"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Логин"))
        self.btn_auto_animaunt.setText(_translate("Form", "Войти"))
        self.btn_auto_malf.setText(_translate("Form", "Войти"))
